-- MySQL Script generated by MySQL Workbench
-- 10/08/15 00:09:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema viandas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema viandas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `viandas` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `viandas` ;

-- -----------------------------------------------------
-- Table `viandas`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viandas`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido` VARCHAR(45) NULL COMMENT '',
  `dni` INT(11) NULL COMMENT '',
  `domicilio` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `estadoDeuda` VARCHAR(45) NULL COMMENT '',
  `valorDeuda` VARCHAR(45) NULL COMMENT '',
  `estado` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viandas`.`dia_semana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viandas`.`dia_semana` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viandas`.`no_laborables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viandas`.`no_laborables` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `motivo` VARCHAR(45) NULL COMMENT '',
  `estado` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viandas`.`tipo_vianda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viandas`.`tipo_vianda` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `precio` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viandas`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viandas`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cantidad` INT(11) NULL COMMENT '',
  `estado` VARCHAR(45) NULL COMMENT '',
  `envio` VARCHAR(45) NULL COMMENT '',
  `cliente_id` INT NOT NULL COMMENT '',
  `tipo_vianda_id` INT NOT NULL COMMENT '',
  `fecha_pedido` DATE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_pedido_cliente1_idx` (`cliente_id` ASC)  COMMENT '',
  INDEX `fk_pedido_tipo_vianda1_idx` (`tipo_vianda_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `viandas`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_tipo_vianda1`
    FOREIGN KEY (`tipo_vianda_id`)
    REFERENCES `viandas`.`tipo_vianda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viandas`.`cliente_dias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viandas`.`cliente_dias` (
  `idcliente_dias` INT NOT NULL COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viandas`.`tipo_alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viandas`.`tipo_alimento` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viandas`.`alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viandas`.`alimento` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `estado` VARCHAR(45) NULL COMMENT '',
  `tipo_alimento_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_alimento_tipo_alimento1_idx` (`tipo_alimento_id` ASC)  COMMENT '',
  CONSTRAINT `fk_alimento_tipo_alimento1`
    FOREIGN KEY (`tipo_alimento_id`)
    REFERENCES `viandas`.`tipo_alimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viandas`.`no_me_gusta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viandas`.`no_me_gusta` (
  `` INT NOT NULL COMMENT '',
  `cliente_id` INT NOT NULL COMMENT '',
  `alimento_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (``)  COMMENT '',
  INDEX `fk_no_me_gusta_cliente_idx` (`cliente_id` ASC)  COMMENT '',
  INDEX `fk_no_me_gusta_alimento1_idx` (`alimento_id` ASC)  COMMENT '',
  CONSTRAINT `fk_no_me_gusta_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `viandas`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_no_me_gusta_alimento1`
    FOREIGN KEY (`alimento_id`)
    REFERENCES `viandas`.`alimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viandas`.`cliente_dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viandas`.`cliente_dia` (
  `cliente_id` INT NOT NULL COMMENT '',
  `dia_semana_id` INT(11) NOT NULL COMMENT '',
  `tipo_vianda_id` INT NOT NULL COMMENT '',
  `cantidad` INT(11) NULL COMMENT '',
  PRIMARY KEY (`cliente_id`, `dia_semana_id`)  COMMENT '',
  INDEX `fk_cliente_has_dia_semana_dia_semana1_idx` (`dia_semana_id` ASC)  COMMENT '',
  INDEX `fk_cliente_has_dia_semana_cliente1_idx` (`cliente_id` ASC)  COMMENT '',
  INDEX `fk_cliente_has_dia_semana_tipo_vianda1_idx` (`tipo_vianda_id` ASC)  COMMENT '',
  CONSTRAINT `fk_cliente_has_dia_semana_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `viandas`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_dia_semana_dia_semana1`
    FOREIGN KEY (`dia_semana_id`)
    REFERENCES `viandas`.`dia_semana` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_dia_semana_tipo_vianda1`
    FOREIGN KEY (`tipo_vianda_id`)
    REFERENCES `viandas`.`tipo_vianda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viandas`.`envios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viandas`.`envios` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `zona` VARCHAR(45) NULL COMMENT '',
  `precio` VARCHAR(45) NULL COMMENT '',
  `observaciones` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
